---
- name: Install Python, pip, and dependencies for Ansible.
  package: "name={{ item }} state=latest"
  with_items: [ 'software-properties-common', 'python-software-properties', 'python-pip' ]

- name: Upgrade pip and install 'setuptools', another Ansible dependency.
  pip: "name={{ item }} state=latest"
  with_items: [ 'pip', 'setuptools' ]
